import { SYSTEM_PROMPT } from './prompt';
import { toolSchemas, executeTool } from './tools';
import type { ChatMessage, ChatTool, TurnContext } from './types';
import type { Store } from './store';
import type { ScheduleStore } from './schedule-store';
import type { DraftStore } from './draft-store';
import type { CustomerStore } from './customer-store';
import type { DailyVolumeStore } from './daily-volume-store';
import type { KycProvider } from './providers/kyc-provider';

const MAX_TOOL_ROUNDS = 6;
const FALLBACK_REPLY =
  "Sorry, I'm having trouble right now. Could you send that again?";

export interface AgentDeps {
  chat: (messages: ChatMessage[], tools: ChatTool[]) => Promise<ChatMessage>;
  store: Store;
  scheduleStore: ScheduleStore;
  draftStore: DraftStore;
  customerStore: CustomerStore;
  dailyVolumeStore: DailyVolumeStore;
  kycProvider: KycProvider;
}

/**
 * Strip every URL the model wrote and optionally append the canonical,
 * code-generated payment link verbatim.
 *
 * The AI model must NEVER be trusted to emit a URL — it can mistype the
 * domain (typo-squatting risk). All payment links come from our code only.
 */
export function sanitizeReply(reply: string, paymentLinks: string[]): string {
  // Strip every URL the model wrote — the model must never emit links itself.
  const stripped = reply
    .replace(/https?:\/\/\S+/gi, '')
    .replace(/[ \t]+/g, ' ')
    .replace(/ *\n/g, '\n')
    .trim();
  if (paymentLinks.length === 0) return stripped;
  // Append the canonical, code-generated link verbatim.
  const link = paymentLinks[paymentLinks.length - 1];
  return `${stripped}\n\n${link}`.trim();
}

export function createAgent(deps: AgentDeps) {
  async function runAgentTurn(
    phone: string,
    incomingText: string,
    turn: TurnContext = { isNewConversation: false },
  ): Promise<string> {
    const history = await deps.store.getConversation(phone);
    history.push({ role: 'user', content: incomingText });

    let reply = '';
    const paymentLinks: string[] = [];

    for (let round = 0; round < MAX_TOOL_ROUNDS; round++) {
      // A one-off system note for new conversations. Not persisted to history
      // (only injected into the messages sent to the model this turn) so it
      // doesn't echo on every later turn.
      const messages: ChatMessage[] = [
        { role: 'system', content: SYSTEM_PROMPT },
      ];
      if (turn.isNewConversation && round === 0) {
        messages.push({
          role: 'system',
          content:
            '[NEW CONVERSATION] This is the first message in over 24 hours. Call list_saved_recipients first; if results exist, call send_recipient_picker.',
        });
      }
      if (round === 0) {
        if (turn.isNewCustomer) {
          messages.push({
            role: 'system',
            content:
              '[NEW CUSTOMER] This is the first message ever from this phone. Greet warmly, mention the $500/day cap for the first 3 days, call check_send_limit({amount_usd: 0}) to fetch the kyc_url, then share that URL and ask how much they want to send.',
          });
        } else if (turn.tierReminderDayOfWindow) {
          messages.push({
            role: 'system',
            content:
              `[TIER_REMINDER day ${turn.tierReminderDayOfWindow}/3] T0 customer in their observation window. Briefly remind them which day they're on and share the kyc_url (from check_send_limit({amount_usd: 0})) before continuing the normal flow.`,
          });
        }
      }
      messages.push(...history);

      const assistant = await deps.chat(messages, toolSchemas);
      history.push(assistant);

      if (assistant.tool_calls && assistant.tool_calls.length > 0) {
        for (const call of assistant.tool_calls) {
          let args: Record<string, unknown> = {};
          try {
            args = JSON.parse(call.function.arguments || '{}');
          } catch {
            args = {};
          }
          const result = await executeTool(call.function.name, args, {
            phone,
            store: deps.store,
            scheduleStore: deps.scheduleStore,
            draftStore: deps.draftStore,
            customerStore: deps.customerStore,
            dailyVolumeStore: deps.dailyVolumeStore,
            kycProvider: deps.kycProvider,
            turn,
          });
          // Collect canonical payment links generated by our code.
          if (
            call.function.name === 'generate_payment_link' &&
            typeof (result as Record<string, unknown>).url === 'string'
          ) {
            paymentLinks.push((result as Record<string, unknown>).url as string);
          }
          history.push({
            role: 'tool',
            tool_call_id: call.id,
            content: JSON.stringify(result),
          });
        }
        continue;
      }

      reply = assistant.content || '';
      break;
    }

    // Apply empty-reply fallback before sanitizing so a payment link is never lost.
    if (!reply) reply = FALLBACK_REPLY;
    // Sanitize: strip model-emitted URLs, append canonical link if present.
    reply = sanitizeReply(reply, paymentLinks);
    await deps.store.saveConversation(phone, history);
    return reply;
  }

  return { runAgentTurn };
}
