import type { MetadataRoute } from 'next';

// /robots.txt (Program-Fix 41, sec-14). Generated by the Next metadata route
// convention (node_modules/next/dist/docs/01-app/03-api-reference/
// 03-file-conventions/01-metadata/robots.md, "Generate a Robots file").
//
// Crawlers are kept out of every capability URL (a /pay, /onboard or
// /partners/apply link IS the credential) and every signed-in tree. robots.txt
// is advisory, not access control: each of these routes still gates itself.
// The canonical host is fixed: previews are behind Vercel Deployment Protection.
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: ['/pay', '/onboard', '/partners/apply', '/account', '/admin-dashboard', '/login', '/api'],
    },
    sitemap: 'https://smartremit.ai/sitemap.xml',
  };
}
